#ifndef COMMON_H
#define COMMON_H

#define SCREEN_WIDTH 600
#define SCREEN_HEIGHT 600
#define LINES_PER_QUADRANT 30
#define LINE_STEP 10
#define LINE_COUNT (LINES_PER_QUADRANT * 2)

#endif /* COMMON_H */
